about:
  summary: "MULTIPLY emulation framework package"
  home: https://github.com/multiply-org/emulation_framework

package:
  name: multiply-emulation-framework
  version: "0.1"

source:
  git_url: "https://github.com/multiply-org/emulation_framework.git"

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
